Style/SymbolArray:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/LineLength:
  Max: 85
  Exclude:
  - rail_feeds.gemspec
Layout/TrailingBlankLines:
  Exclude:
  - rail_feeds.gemspec
Layout/EmptyLines:
  Exclude:
  - spec/**/*
Metrics/BlockLength:
  Exclude:
  - spec/**/*
