require:
  - rubocop-performance
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '*.gemspec'
Style/SignalException:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Max: 17.5
Layout/LineLength:
  Max: 90
  Exclude:
  - rail_feeds.gemspec
  - spec/**/*
Layout/TrailingEmptyLines:
  Exclude:
  - rail_feeds.gemspec
Style/WordArray:
  Exclude:
  - spec/**/*
Layout/EmptyLines:
  Exclude:
  - spec/**/*
Metrics/BlockLength:
  Exclude:
  - spec/**/*
Style/NumericLiterals:
  Exclude:
  - spec/**/*
Security/YAMLLoad:
  Exclude:
  - spec/**/*
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

