language: ruby
rvm:
  - 2.4.4
  - 2.4.5
  - 2.4.6
  - 2.4.7
  - 2.4.8
  - 2.4.9
  - 2.4.10
  - 2.5.0
  - 2.5.1
  - 2.5.2
  - 2.5.3
  - 2.5.4
  - 2.5.5
  - 2.5.6
  - 2.5.7
  - 2.5.8
  - 2.6.0
  - 2.6.1
  - 2.6.2
  - 2.6.3
  - 2.6.4
  - 2.6.5
  - 2.6.6
  - 2.7.0
  - 2.7.1
  - jruby-9.2.0.0
  - jruby-9.2.1.0
  - jruby-9.2.3.0
  - jruby-9.2.4.0
  - jruby-9.2.4.1
  - jruby-9.2.5.0
  - jruby-9.2.6.0
gemfile:
  - Gemfile
branches:
  only:
    - main
    - /gh(?:\d)+(?:-.+)?/
    - /dev_ver_\d+\.\d+/
env:
  global:
    # CC_TEST_REPORTER_ID for reporting test coverage to code climate
    - secure: "FZfolhPdHyjrdWphjAptqMwn/hRNiMZOEtIxZyJO2iWYaVC53L0NTyYl8TTQai38yG5bTuoSvIzPnAzs1HZv+lGnProvfnPJs0uHOyfLCeUkZtbOmHya0/ZeXQ0pQr/sH4C30Vs2TBaK2WOWPDNPoUYhsfbyUrPefSwJU99JhQZMOrbcJUB2VU8w0INs/5dTowQ3LVfVPOP2c4jTNfsXZm9y7OBHvkRwrWWN28fQgvnmdbL+y29+5v49+XIMdNADaVQI+h6g/aTugH3Ld6rowRh52TEr//tOQ205ryYN2i2RA5Cno7kPS/HQbqOf6Hx2aCBItwMaMBkxV0ZQqVkVWk89Kdw3Et0VthTCHsyhZIIikpdavq5F7J0Zfqe1vrNDU3rciIfHaH5TPgBXianAlbEC8/HJSrxPYGKK9XrM7K3zNln/2GNsRGykVUzJSXFvKRKbwrgKg+4nRLYw9LYtQyKWBqPMY1V3pnVPfBJ0W424gY2phuU5gfhib4bm48SiKoMCyCBReOwKhp+P9lDSkiPYLgjADe1L/+DsfltJdAq1sLx+1chLYQYIOMHZM8dGRWqHY+IvAvNrM12B3j8pR4i1ABREgIb6tkWODlSybIqMFekv9NX5ymXoxuIAFi5ony+xWfR47mC1+fkaTaS02WEhyUyBRY4p25LQ9mKZFLs="
before_install: gem update bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && chmod +x ./cc-test-reporter && ./cc-test-reporter before-build
script:
  - bundle exec rubocop
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - secure: CH9idL8/an98uf8uvZ0Pzp7LN9ejdFXh40L6obz5x3tViTzvqo2pqNdryom1E6Dw3NJ7nh4h91XxAq6IZLzrwhSGVGri4tA6EPls6NnkN/UvaK/oCt71ZUaC07hb7SSrc+sQN2CRXMFzxkRBvQ8EKlq+F+Qtj28h0Rebfd79CE+i2NYuAtimYRezOmyLKYUHKRkhYtXbR12FKkNW+2pNNx/Aq02bP/sMXTVdk3k+1bsnpjOoan0m7c2SUkYRD9vmY4u9vxTt2lFFJ+V5NWntXb3y5ttctR9EukULHS2mqFA4q+i6OAJaJUIGWCeWTsB1V3fPuICcZHPV1gF4wVAfV/xees1STJuzGRBpIRTUPd/iXfnNT35e5o97quSHolYx0nCRstonW8IOwlegDqJCbmu8nAaP2M42VkZ4u0Qi1MgzFZ3XcmlLsIrypQHbLnQZKgcnBPxY/8AuqDY9JgiY9RaTMT5xyPox33yAC41MaNYouicyfFSZ4Q+4QFNaPtjaG+N5VR7neMGa5uCXGFHR8H5pWDV5oUFlZzep3bMnrkT9nb/56UjZlAF94nYPEs0nsEm+r35b/g/WWGB+t8UpHzl/jK0s74NbASu+MyNN6X+FiaxOB3WvaFz0wJNqN46SINJjHk1CDhquD1qoyLI+R6AtrRkFvlgaXf6RCSfsWCo=
