language: ruby
rvm:
  - 2.4.4
  - 2.4.5
  - 2.4.6
  - 2.5.0
  - 2.5.1
  - 2.5.2
  - 2.5.3
  - 2.5.4
  - 2.5.5
  - 2.6.0
  - 2.6.1
  - 2.6.2
  - 2.6.3
  - jruby-9.2.0.0
  - jruby-9.2.1.0
  - jruby-9.2.3.0
  - jruby-9.2.4.0
  - jruby-9.2.4.1
  - jruby-9.2.5.0
  - jruby-9.2.6.0
gemfile:
  - Gemfile
branches:
  only:
    - master
    - staging
    - /gh(?:\d)+(?:-.+)?/
    - /dev_ver_\d+\.\d+/
env:
  global:
    # CC_TEST_REPORTER_ID for reporting test coverage to code climate
    - secure: "LJDr3rGTkn3gi8Vpvo2LdgvgjfuJHbPD7LIHNfhn+WtjoIXRCBom+CiB8OvStwxHnmK+KkaFK3RJgYSVs7QjgGFquuyVlWnWLU1uJBElZgSHhcgPcenjvzT8GglxR1JBJF322iPblqNDfTaplJw7rNt78dxrJhkCKD8lybwYoE/ops6p510pVsaV44m+N5qcYd8w9WTUhXIr0KZB2bDLAkkZAvdqOrN3qFM/fsnnzzn+EKI3QSxWgfGTzVMlhHPLntsY1DdVvmdK0cDo0jxJ0CbRdkt4XFGfwbSBF2llZ/Mbw7AOm0Ej7xT/Ge6hhg9+hOkrgsd4F0pnmQD8mh5ZR1lCQBCA8D8AHJFUv63bG1GoHs77X5fUNet+NQOnCgs7Xmp7YUYEg8ZqSRqw3FWJ7xn/H9K9s3rHZ3cgQXi+L+ZRocSMnVqEe9BupkgKW6jxtu0RS1Do7jXj32wnNOQoXKRxEdEzvXZyp1XLYw4H2SZkfw8ig3KK0wd8qzBUTVvZCluoOYSvd6AMzf3ZBaKE+r/3HI5M5mW0oCQQPWbz6f3fIlMeRUajzwSiabdRPLT/15FD17OygkhKA0OdIHywQJCmGzjf1r86qxpZXxFjr2+ePQRTH+/3Oj3r4Yb8IkhYnA1gNZgxtnaQSDFcjoFmLwHX2Hx8B9lTTV1teTq7xXc="
before_install: gem update bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && chmod +x ./cc-test-reporter && ./cc-test-reporter before-build
script:
  - bundle exec rubocop
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - secure: CH9idL8/an98uf8uvZ0Pzp7LN9ejdFXh40L6obz5x3tViTzvqo2pqNdryom1E6Dw3NJ7nh4h91XxAq6IZLzrwhSGVGri4tA6EPls6NnkN/UvaK/oCt71ZUaC07hb7SSrc+sQN2CRXMFzxkRBvQ8EKlq+F+Qtj28h0Rebfd79CE+i2NYuAtimYRezOmyLKYUHKRkhYtXbR12FKkNW+2pNNx/Aq02bP/sMXTVdk3k+1bsnpjOoan0m7c2SUkYRD9vmY4u9vxTt2lFFJ+V5NWntXb3y5ttctR9EukULHS2mqFA4q+i6OAJaJUIGWCeWTsB1V3fPuICcZHPV1gF4wVAfV/xees1STJuzGRBpIRTUPd/iXfnNT35e5o97quSHolYx0nCRstonW8IOwlegDqJCbmu8nAaP2M42VkZ4u0Qi1MgzFZ3XcmlLsIrypQHbLnQZKgcnBPxY/8AuqDY9JgiY9RaTMT5xyPox33yAC41MaNYouicyfFSZ4Q+4QFNaPtjaG+N5VR7neMGa5uCXGFHR8H5pWDV5oUFlZzep3bMnrkT9nb/56UjZlAF94nYPEs0nsEm+r35b/g/WWGB+t8UpHzl/jK0s74NbASu+MyNN6X+FiaxOB3WvaFz0wJNqN46SINJjHk1CDhquD1qoyLI+R6AtrRkFvlgaXf6RCSfsWCo=
